language: python

python:
  - 2.6
  - 2.7
  - 3.2

install:
  # numpy has a known bug that it won't install properly from within distutils
  - pip install numpy
  - python setup.py install

script: python collada
