language: python

env:
  - DEPS=""
  - DEPS="lxml"

python:
  - 2.6
  - 2.7
  - 3.2

install:
  # temporary workaround for numpy failing in virtualenv
  # https://github.com/travis-ci/travis-cookbooks/issues/48#issuecomment-10843018
  - export PYTHONIOENCODING=UTF8 # just in case
  - 'if [ $TRAVIS_PYTHON_VERSION == "3.2" ] || [ $TRAVIS_PYTHON_VERSION == "3.1" ]; then pip install https://github.com/y-p/numpy/archive/1.6.2_with_travis_fix.tar.gz; fi'
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install numpy; fi' # should be nop if pre-installed
  - pip install $DEPS
  - python setup.py install

script: python collada
